"""
主窗口协议接口 - 定义所有控制器对主窗口的依赖契约
控制器应依赖此 Protocol 而非具体的 IPTVPlayer 类
"""

from typing import Protocol, Any, Optional, List, Dict, runtime_checkable

from PyQt6.QtWidgets import QStatusBar, QWidget, QSlider, QPushButton, QLabel, QListWidget, QComboBox, QTabWidget, QProgressBar, QLineEdit, QToolBar
from PyQt6.QtCore import Qt


@runtime_checkable
class MainWindowProtocol(Protocol):
    """主窗口协议 - 控制器通过此协议访问主窗口"""

    # === Qt 内置方法 ===
    def setWindowTitle(self, title: str) -> None: ...
    def windowTitle(self) -> str: ...
    def setWindowFlag(self, flag: Qt.WindowType, on: bool = True) -> None: ...
    def windowFlags(self) -> Qt.WindowType: ...
    def setMinimumSize(self, w: int, h: int) -> None: ...
    def setMaximumSize(self, w: int, h: int) -> None: ...
    def resize(self, w: int, h: int) -> None: ...
    def move(self, x: int, y: int) -> None: ...
    def show(self) -> None: ...
    def showNormal(self) -> None: ...
    def showMaximized(self) -> None: ...
    def showMinimized(self) -> None: ...
    def close(self) -> None: ...
    def raise_(self) -> None: ...
    def setMouseTracking(self, enable: bool) -> None: ...
    def setCursor(self, cursor: Any) -> None: ...
    def unsetCursor(self) -> None: ...
    def isActiveWindow(self) -> bool: ...
    def isMaximized(self) -> bool: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def setGeometry(self, *args) -> None: ...
    def setStyleSheet(self, style: str) -> None: ...
    def thread(self) -> Any: ...
    def childAt(self, x: int, y: int) -> Any: ...
    def frameGeometry(self) -> Any: ...
    def geometry(self) -> Any: ...
    def screen(self) -> Any: ...
    def cursor(self) -> Any: ...
    def rect(self) -> Any: ...
    def mapFromGlobal(self, pos: Any) -> Any: ...
    def findChildren(self, type: Any) -> List[Any]: ...

    # === 业务方法 ===
    def status_bar_show_message(self, message: str, timeout: int = 0) -> None: ...
    def _populate_channel_list(self, *args, **kwargs) -> None: ...
    def _populate_epg_list(self, *args, **kwargs) -> None: ...
    def populate_channel_list(self, *args, **kwargs) -> None: ...
    def populate_epg_list(self, *args, **kwargs) -> None: ...
    def play_channel(self, *args, **kwargs) -> None: ...
    def update_channel_info_on_selection(self) -> None: ...
    def _set_progress_value(self, *args, **kwargs) -> None: ...
    def _set_progress_range(self, *args, **kwargs) -> None: ...
    def _cancel_source_timeout(self) -> None: ...
    def _on_mouse_activity(self) -> None: ...
    def _delayed_hide_floating_panels(self) -> None: ...
    def _show_floating_panels_on_enter(self) -> None: ...
    def update_floating_position(self) -> None: ...
    def raise_floating_panels(self) -> None: ...
    def _on_main_window_activated(self) -> None: ...
    def _on_main_window_deactivated(self) -> None: ...
    def _stop_auto_hide_timer(self) -> None: ...
    def _restart_auto_hide_timer(self) -> None: ...
    def _sync_panel_actions(self) -> None: ...
    def toggle_mute(self) -> None: ...
    def toggle_fullscreen(self) -> None: ...
    def toggle_epg(self) -> None: ...
    def toggle_playlist(self) -> None: ...
    def toggle_floating_panel(self) -> None: ...
    def toggle_hide_floating(self) -> None: ...
    def reset_layout(self) -> None: ...
    def _open_stream(self, *args, **kwargs) -> None: ...
    def _open_video_file(self, *args, **kwargs) -> None: ...
    def open_scan_ui(self) -> None: ...
    def _show_osd_feedback(self, *args, **kwargs) -> None: ...
    def setup_menu_bar(self) -> None: ...
    def _center_dialog_on_screen(self, *args, **kwargs) -> None: ...
    def _handle_playlist_subscription(self, *args, **kwargs) -> None: ...
    def _do_on_playlist_updated_in_main_thread(self, *args, **kwargs) -> None: ...
    def _update_groups_for(self, *args, **kwargs) -> None: ...
    def _reapply_side_panel_styles(self) -> None: ...
    def _reapply_floating_panel_styles(self) -> None: ...
    def _raise_floating_panels(self) -> None: ...
    def wheelEvent(self, event: Any) -> None: ...
    def mouseDoubleClickEvent(self, event: Any) -> None: ...

    # === UI 控件 ===
    status_bar: QStatusBar
    video_widget: QWidget
    video_placeholder: QWidget
    video_frame: QWidget
    channel_list: QListWidget
    channel_name: QLabel
    channel_logo: QLabel
    video_info: QLabel
    audio_info: QLabel
    network_info: QLabel
    current_program: QLabel
    program_desc: QLabel
    time_label: QLabel
    remain_label: QLabel
    program_progress: QProgressBar
    progress_start: QLabel
    progress_end: QLabel
    play_button: QPushButton
    volume_slider: QSlider
    volume_button: QPushButton
    speed_button: QPushButton
    exit_catchup_button: QPushButton
    group_combo: QComboBox
    playlist_tab: QTabWidget
    floating_panel: QWidget
    epg_panel: QWidget
    epg_content: QWidget
    epg_empty_label: QLabel
    epg_date_label: QLabel
    epg_dock: QWidget
    playlist_dock: QWidget
    floating_dock: QWidget
    toolbar: QToolBar
    central_widget: QWidget
    _title_bar: QWidget
    _title_label: QLabel
    _custom_menu_bar: QWidget
    _osd_menu_action: Any
    _pip_menu_action: Any
    _epg_menu_action: Any
    _playlist_menu_action: Any
    _floating_menu_action: Any
    _fullscreen_menu_action: Any
    audio_track_button: QPushButton
    sub_track_button: QPushButton
    aspect_button: QPushButton
    playlist_list_widget: QListWidget
    epg_list_widget: QListWidget
    playlist_new_url_edit: QLineEdit
    playlist_new_name_edit: QLineEdit
    _playlist_add_btn: QPushButton
    epg_new_url_edit: QLineEdit
    epg_new_name_edit: QLineEdit
    _epg_add_btn: QPushButton

    # === 状态变量 ===
    current_channel: Optional[Dict[str, Any]]
    channels: List[Dict[str, Any]]
    _local_channels: List[Dict[str, Any]]
    _sub_channels: List[Dict[str, Any]]
    original_channel: Optional[Dict[str, Any]]
    catchup_program: Optional[Any]
    _live_timeshift_seconds: float
    current_epg_date: str
    _osd_visible: bool
    _progress_total_seconds: float
    _progress_time_mode: str
    _progress_program_start: float
    _progress_program_end: float
    _initial_position_fixed: bool
    _floating_hidden: bool
    _auto_hide_state: str
    is_fullscreen: bool
    pip_mode: bool
    epg_visible: bool
    playlist_visible: bool
    floating_panel_visible: bool

    # === 服务/控制器引用 ===
    language_manager: Any
    player_controller: Any
    play_state: Any
    panel_vis: Any
    config: Any
    channel_model: Any
    epg_parser: Any
    channel_ctrl: Any
    epg_ctrl: Any
    playback_ctrl: Any
    catchup_ctrl: Any
    pip_ctrl: Any
    media_ctrl: Any
    event_handler: Any
    subscription_ctrl: Any
    subscription_ui_ctrl: Any
    settings_ops: Any
    update_ctrl: Any
    favorites_ctrl: Any
    epg_reminder_ctrl: Any

    _thumbnail_service: Any
    _scan_dialog: Any
    scan_window: Any
    config_manager: Any

    fav_channel_list: Any
    fav_empty_label: Any
    history_channel_list: Any
    history_empty_label: Any
