import os
import threading
from typing import overload
from core.log_manager import LogManager
from PyQt6.QtCore import QObject, pyqtSignal
from utils.singleton import Singleton

logger = LogManager()

BUILTIN_TRANSLATIONS = {
    'zh': {
        'language_name': '中文',
        'app_title': 'IPTV扫描编辑器专业版',
        'video_playback': '视频播放',
        'play': '播放',
        'pause': '暂停',
        'stop': '停止',
        'volume': '音量',
        'scan_settings': '扫描设置',
        'address_format': '地址格式',
        'address_example': '地址示例',
        'input_address': '输入地址',
        'timeout_description': '设置扫描超时时间（秒）',
        'thread_count_description': '设置扫描线程数',
        'user_agent': 'User-Agent',
        'referer': 'Referer',
        'progress': '进度',
        'timeout': '超时',
        'thread_count': '线程数',
        'scan_timeout': '超时(秒):',
        'scan_threads': '线程数:',
        'full_scan': '完整扫描',
        'stop_scan': '停止扫描',
        'generate_list': '生成列表',
        'total_channels': '总数',
        'valid': '有效',
        'invalid': '无效',
        'time_elapsed': '耗时',
        'channel_list': '频道列表',
        'validate_effectiveness': '检测有效性',
        'hide_invalid': '隐藏无效项',
        'smart_sort': '智能排序',
        'please_load_list': '请先加载列表',
        'channel_edit': '频道编辑',
        'channel_name': '频道名称',
        'channel_group': '频道分组',
        'logo_address': 'Logo地址',
        'channel_url': '频道URL',
        'edit_channel': '编辑频道',
        'add_channel': '添加频道',
        'operation': '操作',
        'open_list': '打开列表',
        'save_list': '保存列表',
        'language': '语言',
        'about': '关于',
        'required': '必填',
        'optional': '可选',
        'optional_default': '可选，为空使用默认值',
        'optional_not_used': '可选，为空不使用',
        'serial_number': '序号',
        'resolution': '分辨率',
        'status': '状态',
        'latency_ms': '延迟(ms)',
        'tvg_id': 'TVG-ID',
        'tvg_chno': 'TVG频道号',
        'tvg_shift': 'TVG时移',
        'catchup': '回看',
        'catchup_days': '回看天数',
        'catchup_source': '回看源',
        'catchup_correction': '回看时区修正',
        'about_dialog_title': '关于 IPTV Scanner Editor Pro',
        'current_version': '当前版本',
        'latest_version': '最新版本',
        'build_date': '编译日期',
        'qt_version': 'QT版本',
        'close_button': '关闭',
        'checking_update': '检测中...',
        'update_timeout': '请求超时',
        'update_failed': '获取失败',
        'api_limit': 'API限制',
        'update_progress_title': '在线更新',
        'update_checking': '正在检查更新...',
        'update_downloading': '正在下载更新...',
        'update_complete': '更新下载完成，请重启应用',
        'update_error': '更新失败',
        'network_error': '网络错误',
        'feature_intro': '主要功能说明',
        'smart_scan': '智能频道扫描',
        'advanced_validation': '高级流验证',
        'intelligent_management': '智能频道管理',
        'integrated_playback': '集成视频播放',
        'advanced_config': '高级配置管理',
        'professional_tools': '专业工具集成',
        'usage_method': '使用方法',
        'scan_usage': '在扫描设置中输入地址格式，点击"完整扫描"开始',
        'validation_usage': '打开播放列表后点击"检测有效性"按钮',
        'management_usage': '右键频道列表或拖拽调整顺序',
        'playback_usage': '双击频道列表中的任意频道',
        'config_usage': '所有设置自动保存，无需手动操作',
        'tools_usage': '通过工具栏访问各专业工具',
        'cancel_button': '取消',
        'update_success': '更新完成',
        'file': '文件',
        'edit': '编辑',
        'view': '视图',
        'tools': '工具',
        'help': '帮助',
        'new_playlist': '新建播放列表',
        'open_playlist': '打开播放列表',
        'save_playlist': '保存播放列表',
        'save_as': '另存为...',
        'import_channels': '导入频道',
        'export_channels': '导出频道',
        'exit': '退出',
        'undo': '撤销',
        'redo': '重做',
        'select_all': '全选',
        'delete_selected': '删除选中',
        'show_epg': '显示节目单',
        'show_playlist': '显示播放列表',
        'fullscreen': '全屏模式',
        'refresh': '刷新',
        'reset_layout': '重置布局',
        'scan_channels': '扫描整理',
        'verify_channels': '验证频道',
        'restore_hidden': '恢复隐藏项',
        'channel_management': '频道管理',
        'channel_mapping': '频道映射',
        'favorite_management': '收藏管理',
        'network_settings': '网络设置',
        'player_settings': '播放器设置',
        'usage_instructions': '使用说明',
        'chinese': '中文',
        'english': 'English',
        'loading_channels': '正在加载频道...',
        'channels_loaded': '成功加载 {count} 个频道',
        'file_format_error': '文件格式不正确或为空',
        'open_file_error': '打开文件失败: {error}',
        'save_success': '保存成功',
        'save_error': '保存文件失败: {error}',
        'no_content': '没有可保存的内容',
        'file_selection_error': '文件选择失败: {error}',
        'app_name': 'IPTV Scanner Editor Pro',
        'version': '版本 1.0.0',
        'description': 'IPTV 频道扫描和编辑工具',
        'usage_title': '使用说明',
        'usage_content': '## 基本操作\n\n### 1. 打开播放列表\n- 点击"文件"菜单 → "打开播放列表"（Ctrl+O）\n- 支持 M3U、M3U8、TXT 格式\n- 也可将文件直接拖放到主窗口打开\n\n### 2. 播放频道\n- 在频道列表中**双击**频道开始播放\n- 底部控制面板：▶ 播放 / ▮▮ 暂停 / ■ 停止\n- 音量滑块调节音量，点击图标静音/取消静音\n- 倍速按钮切换播放速度，比例按钮切换画面比例\n- 全屏按钮或 F11 进入全屏\n- **↑ ↓** 键切换频道，**← →** 键调整音量\n\n### 3. EPG 电子节目单\n- 左侧面板显示当前频道节目安排\n- 点击 ◀ / ▶ 切换日期查看节目\n- 进度条实时显示当前节目播放进度\n- 支持配置 EPG 数据源自动订阅更新\n- M3U 文件头中的 EPG 地址会自动加载\n\n### 4. 扫描整理\n- 工具菜单 → 扫描整理\n- 输入 IP 范围或流地址（如 `239.3.1.[1-100]:8000`）\n- 设置超时时间和线程数，支持追加扫描和重试\n- 扫描完成后可使用**批量操作**：\n  - **自动分类**：根据频道名称规则自动归类分组\n  - **清理名称**：去除多余括号、HD后缀等，规范化频道名\n  - **匹配台标**：批量匹配频道台标图片\n  - **分配字段**：批量设置分组、台标等属性\n  - **按组排序**：按频道分组自动排序\n\n### 5. 验证频道\n- 批量检测频道有效性，显示延迟、分辨率等参数\n- 支持智能重试失败的项\n\n### 6. 频道管理\n- **拖拽排序**：拖动调整频道顺序\n- **分组筛选**：下拉框按分组过滤频道\n- **右键菜单**：删除、复制、清理名称、匹配台标等操作\n- **频道分类**：基于正则规则自动归类到对应分组\n- **名称清理**：智能去除冗余信息，规范化显示\n- **导出保存**：另存为 M3U / TXT / Excel 格式\n\n## 高级功能\n\n### 订阅设置\n- 工具菜单 → 订阅设置\n- 配置多个播放列表源和 EPG 数据源，独立管理\n- 支持过期自动刷新和增量更新\n- RTSP 传输方式可选 TCP/UDP/LAVF\n\n### 频道映射\n- 工具菜单 → 频道映射管理器\n- 可视化编辑频道名称、LOGO、分组的映射规则\n\n### 文件关联\n- 工具菜单 → 文件关联\n- 勾选需要关联的格式（M3U/M3U8/TXT/视频格式）\n- 关联后可从资源管理器右键打开\n\n### 界面定制\n- **主题切换**：5 种主题即时切换\n- **语言切换**：中文 / English\n- **面板控制**：视图菜单或快捷键\n  - **E** — EPG 节目单面板\n  - **L** — 频道列表面板\n  - **M** — 播放控制面板\n  - **Y** — 隐藏/恢复所有悬浮面板\n  - **Tab** — 切换 OSD 信息遮罩\n- **F5** 刷新界面，**F11** 全屏，**Ctrl+Q** 退出\n\n### 时移/回看\n- 支持多种回看类型：default / append / shift / flussonic / xc\n- 时间变量替换支持自定义格式和时区偏移\n- M3U 文件头可定义全局回看参数',
        'about_title': '关于',
        'about_content': 'IPTV Scanner Editor Pro\n版本 1.0.0\n\nIPTV 频道扫描和编辑工具\n\n© 2026 IPTV Scanner Editor Pro',
        'epg_title': '节目单',
        'not_playing': '未播放',
        'language_changed': '语言已切换',
        'no_epg_data': '暂无节目信息',
        'no_channels': '暂无频道',
        'media_info': '媒体信息',
        'menu_file': '文件',
        'menu_open_playlist': '打开列表\tCtrl+O',
        'menu_open_stream': '打开串流\tCtrl+U',
        'menu_open_video': '打开视频\tCtrl+Shift+O',
        'open_stream': '打开串流',
        'open_stream_url': '请输入直播地址或串流URL:',
        'open_video': '打开视频',
        'video_files': '视频文件 (*.mp4 *.mkv *.avi *.mov *.flv *.wmv *.ts *.webm);;所有文件 (*)',
        'temp_stream': '临时串流',
        'stream_name_optional': '频道名称（可选）:',
        'stream_name_hint': '留空则自动命名',
        'cancel': '取消',
        'ok': '确定',
        'local_video': '本地视频',
        'local_video_file': '本地视频文件',
        'menu_recent_open': '最近打开',
        'menu_save_as': '另存为...\tCtrl+S',
        'menu_exit': '退出\tCtrl+Q',
        'menu_view': '视图',
        'menu_epg_list': '节目列表\tE',
        'menu_playlist': '播放列表\tL',
        'menu_control_panel': '控制面板\tM',
        'menu_fullscreen': '全屏模式\tF11',
        'menu_pip': '画中画\tP',
        'menu_multi_screen': '多画面',
        'menu_multi_2x2': '2×2 (4画面)',
        'menu_multi_3x3': '3×3 (9画面)',
        'menu_multi_exit': '退出多画面',
        'multi_screen_entered': '已进入多画面模式',
        'multi_screen_exited': '已退出多画面模式',
        'search_channel': '搜索频道...',
        'epg_no_catchup': '该频道不支持回看',
        'epg_upcoming': '节目尚未开始',
        'epg_date_limit': '已到日期范围边界',
        'exit_catchup': '退出回看',
        'panel_prev_ch': '上一频道',
        'panel_next_ch': '下一频道',
        'panel_pip': '画中画',
        'tooltip_minimize': '最小化',
        'tooltip_maximize': '最大化',
        'tooltip_close': '关闭',
        'menu_refresh': '刷新界面\tF5',
        'menu_reset_layout': '重置布局',
        'menu_playback': '播放',
        'menu_prev_channel': '上一个频道\t↑',
        'menu_next_channel': '下一个频道\t↓',
        'menu_prev_channel2': '上一个频道(备选)\tCtrl+Shift+↑',
        'menu_next_channel2': '下一个频道(备选)\tCtrl+Shift+↓',
        'menu_back_channel': '切回上一频道\tBackspace',
        'menu_play_pause': '播放/暂停\tSpace',
        'menu_stop': '停止\tEsc',
        'menu_seek_back': '快退\t←',
        'menu_seek_forward': '快进\t→',
        'menu_vol_up': '音量+\t滚轮↑',
        'menu_vol_down': '音量-\t滚轮↓',
        'menu_mute': '静音\tCtrl+M',
        'menu_speed_up': '加速\t.',
        'menu_speed_down': '减速\t,',
        'menu_screenshot': '截图\tS',
        'osd_volume': '音量',
        'osd_muted': '已静音',
        'osd_speed': '速度',
        'osd_audio_track': '音频',
        'osd_audio_track_failed': '音频切换失败',
        'osd_subtitle_track': '字幕',
        'osd_subtitle_track_failed': '字幕切换失败',
        'ctx_pause': '暂停',
        'ctx_play': '播放',
        'ctx_stop': '停止',
        'ctx_prev_channel': '上一个频道',
        'ctx_next_channel': '下一个频道',
        'ctx_speed': '速度',
        'ctx_volume': '音量',
        'ctx_mute': '静音',
        'ctx_unmute': '取消静音',
        'ctx_aspect_ratio': '宽高比',
        'ctx_aspect_default': '默认',
        'ctx_aspect_stretch': '拉伸',
        'ctx_aspect_fill': '填充',
        'ctx_screenshot': '截图\tS',
        'ctx_fullscreen': '全屏\tF11',
        'ctx_pip': '画中画\tP',
        'ctx_view': '视图',
        'ctx_epg': '节目单\tE',
        'ctx_playlist': '播放列表\tL',
        'ctx_control_panel': '控制面板\tM',
        'ctx_hide_panels': '隐藏悬浮窗\tY',
        'ctx_reset_layout': '重置布局',
        'ctx_open_stream': '打开串流\tCtrl+U',
        'ctx_open_video': '打开视频\tCtrl+Shift+O',
        'ctx_scan': '扫描整理',
        'ctx_audio_track': '音轨',
        'ctx_no_audio_track': '无音轨',
        'ctx_subtitle': '字幕',
        'ctx_no_subtitle': '无字幕',
        'ctx_load_subtitle': '加载外部字幕...',
        'ctx_subtitle_files': '字幕文件',
        'ctx_all_files': '所有文件',
        'panel_audio_track': '音轨',
        'panel_subtitle': '字幕',
        'menu_tools': '工具',
        'menu_scan_channels': '扫描整理',
        'menu_mapping': '映射管理',
        'menu_subscription_settings': '订阅设置',
        'menu_file_association': '文件关联',
        'file_assoc_title': '选择要关联的文件格式',
        'file_assoc_hint': '注册后，右键文件即可在\u201c打开方式\u201d中选择本程序',
        'file_association': '文件关联',
        'menu_theme': '主题',
        'menu_help': '帮助',
        'menu_instructions': '说明',
        'menu_about': '关于',
        'today': '今天',
        'yesterday': '昨天',
        'tomorrow': '明天',
        'no_channel_selected': '未选择频道',
        'select_channel_to_play': '请选择频道开始播放',
        'open_playlist_or_import': '打开播放列表文件或导入频道以开始观看',
        'waiting_to_play': '等待播放...',
        'exit_catchup': '退出回看',
        'playing': '正在播放',
        'paused': '已暂停',
        'stopped': '已停止',
        'play_error': '播放错误',
        'pip_mode': '画中画模式',
        'to_exit': '退出',
        'pip_exited': '已退出',
        'playing_channel': '正在播放: {name}',
        'paused_channel': '已暂停: {name}',
        'stopped_play': '停止播放',
        'playback_stopped': '播放已停止',
        'catchup_playing': '正在回看: {name}',
        'catchup_paused': '已暂停回看: {name}',
        'subscription_settings_title': '订阅设置',
        'protocol_settings': '回放协议设置',
        'protocol_type': '协议类型',
        'rtsp_transport_colon': 'RTSP传输方式:',
        'hwdec_label': '硬件解码',
        'tls_verify_label': 'TLS验证',
        'network_timeout_colon': '网络超时:',
        'auto_timeout': '自动',
        'playlist_subscription': '列表订阅设置',
        'subscription_url': '订阅地址',
        'subscription_name': '订阅名称',
        'update_interval': '更新间隔(分钟)',
        'epg_subscription': '节目单订阅设置（所有源将自动整合）',
        'playlist_sources': '直播源列表（点击切换启用）：',
        'epg_sources': 'EPG源列表：',
        'add_source': '+ 添加源',
        'update_source': '✎ 更新',
        'remove_source': '- 删除选中',
        'enter_source_name': '源名称（可选）',
        'epg_loaded': 'EPG数据加载成功',
        'save_button': '保存',
        'usage_instructions_title': '使用说明',
        'ok_button': '确定',
        'loading': '加载中...',
        'current_program': '正在播放',
        'upcoming_program': '即将播放',
        'finished_program': '已结束',
        'bitrate_unknown': '未知',
        'codec_unknown': '未知',
        'resolution_unknown': '未知',
        'back_to_live': '返回直播',
        'cannot_seek_live': '无法回退：直播流缓冲区不足（请稍后再试）',
        'timeshift_beyond_cache': '超出缓冲范围，无法跳转到更早时间',
        'timeshift_beyond_cache_no_epg': '超出缓冲范围，无节目信息，无法自动时移',
        'timeshift_playing': '正在时移',
        'ready': '就绪',
        'catchup_not_supported': '该频道不支持回看',
        'playlist_sub_updated': '列表订阅更新成功',
        'playlist_sub_parse_failed': '列表订阅内容解析失败',
        'playlist_sub_update_failed': '更新列表订阅失败',
        'player_settings_saved': '播放器设置保存成功',
        'player_settings_save_failed': '保存播放器设置失败',
        'epg_settings_saved': 'EPG节目单设置已保存',
        'file_opened': '成功打开文件',
        'file_open_failed': '打开文件失败',
        'file_not_found': '文件不存在，已从最近列表移除',
        'language_change_failed': '切换语言失败',
        'theme_changed': '主题已切换为',
        'theme_change_failed': '切换主题失败',
        'epg_sub_updated': '节目单订阅更新成功',
        'epg_sub_parse_failed': '节目单订阅内容解析失败',
        'epg_sub_update_failed': '更新节目单订阅失败',
        'epg_using_cache': '使用缓存的EPG数据',
        'codec_label': '编码',
        'resolution_label': '分辨率',
        'bitrate_label': '码率',
        'channel_count_label': '声道',
        'sample_rate_label': '采样率',
        'format_label': '格式',
        'protocol_label': '协议',
        'frame_rate_label': '帧率',
        'hwdec_label': '硬解',
        'vcodec_label': '视频',
        'acodec_label': '音频',
        'hdr_label': '动态范围',
        'no_video_info': '无视频信息',
        'no_audio_info': '无音频信息',
        'no_network_info': '无网络信息',
        'pixel_format_label': '像素格式',
        'hdr_type': '动态范围',
        'hdr_sdr': 'SDR',
        'hdr_hlg': 'HLG',
        'hdr_hdr10': 'HDR10',
        'hdr_hdr10_plus': 'HDR10+',
        'hdr_dv': '杜比视界',
        'player_settings_title': '播放器设置',
        'update_interval_minutes': '更新间隔时间 (分钟)',
        'enter_playlist_url': '请输入列表订阅地址',
        'enter_subscription_name': '请输入订阅名称',
        'enter_epg_url': '请输入节目单订阅地址',
        'epg_settings_title': 'EPG节目单设置',
        'epg_url_label': 'EPG节目单URL',
        'epg_source_label': 'EPG节目单来源',
        'app_description': 'IPTV 专业扫描编辑工具',
        'system_info': '系统信息',
        'copyright_text': '© 2025 IPTV Scanner Editor Pro 版权所有',
        'github_repo': 'GitHub 仓库',
        'request_timeout_text': '(请求超时)',
        'fetch_failed_text': '(获取失败)',
        'api_limit_text': '(API限制)',
        'scan_settings_title': '扫描设置',
        'channel_list_title': '频道列表',
        'channel_edit_title': '频道编辑',
        'scan_window_title': 'IPTV 扫描器',
        'validate_button': '检测',
        'hide_invalid_button': '隐藏无效',
        'save_m3u': '保存M3U',
        'save_txt': '保存TXT',
        'save_m3u_tooltip': '保存频道列表为M3U格式',
        'save_txt_tooltip': '保存频道列表为TXT格式',
        'batch_ops': '批量操作',
        'batch_ops_tooltip': '频道批量操作',
        'auto_classify': '自动分组',
        'clean_names': '清洗名称',
        'assign_fields': '字段赋值',
        'match_logo': '匹配Logo',
        'clear_params': '清除参数',
        'sort_by_group': '按分组排序',
        'local_province': '本地省份:',
        'overwrite_existing': '覆盖已有分组',
        'merge_nonlocal': '非本地省份归入其他',
        'preview_count': '预览:',
        'channel_name': '频道名称',
        'old_group': '原分组',
        'new_group': '新分组',
        'preview': '预览',
        'apply': '应用',
        'cancel': '取消',
        'before': '修改前',
        'after': '修改后',
        'only_empty_fields': '仅对空字段赋值',
        'target_channels': '目标:',
        'overwrite_logo_confirm': '是否覆盖已有Logo?',
        'move_to_group': '移至分组...',
        'clean_selected_names': '清洗选中名称',
        'match_selected_logo': '匹配选中Logo',
        'target_group': '目标分组:',
        'save_scan_result': '保存扫描结果',
        'no_channels_to_save': '没有可保存的频道',
        'append_scan': '追加扫描',
        'address_format_hint': '格式: http://ip:port/rtp/10.10.[1-20].[1-20]:5002',
        'timeout_small': '超时',
        'thread_small': '线程',
        'scan_retry_options': '扫描重试选项',
        'enable_smart_retry': '启用智能重试扫描',
        'mapping_options': '映射功能选项',
        'enable_channel_mapping': '启用频道映射',
        'save_changes': '保存修改',
        'copy_channel_name': '复制频道名',
        'copy_url': '复制URL',
        'copy_tvg_id': '复制TVG-ID',
        'copy_group': '复制分组',
        'delete_channel': '删除频道',
        'confirm_delete': '确认删除',
        'confirm_delete_mapping': '确认删除映射',
        'confirm_delete_message': '确定要删除选中的频道吗？',
        'select_mapping_to_edit': '请先选择要编辑的映射',
        'select_mapping_to_delete': '请先选择要删除的映射',
        'delete_mapping_confirm': "确定要删除映射 '{}' → '{}'？",
        'scan_complete': '扫描完成',
        'append_scan_tooltip': '不清空现有列表，扫描到的有效频道直接追加到列表末尾',
        'smart_retry_tooltip': '基于失败原因智能重试：只重试超时、连接失败等临时错误，不重试TCP失败、404等永久错误。启用后会自动循环重试直到没有新的有效频道',
        'mapping_tooltip': '启用后，扫描到的频道会根据映射文件自动匹配频道名称、Logo、分组等信息',
        'set_scan_timeout': '设置扫描超时时间（秒）',
        'set_scan_threads': '设置扫描使用的线程数量',
        'validate_tooltip': '检测频道有效性',
        'no_recent_files': '无最近打开的文件',
        'select_channel_play': '请选择频道播放',
        'open_playlist_success': '打开播放列表文件成功，点击频道开始播放',
        'catchup_playing_label': '正在回看',
        'unknown_channel': '未知频道',
        'unnamed': '未命名',
        'uncategorized': '未分类',
        'all_channels': '全部频道',
        'subscription_tab': '订阅',
        'local_tab': '本地',
        'media_info_label': '媒体信息',
        'epg_url_colon': 'EPG节目单URL:',
        'epg_source_colon': 'EPG节目单来源:',
        'protocol_type_colon': '协议类型:',
        'subscription_url_colon': '订阅地址:',
        'subscription_name_colon': '订阅名称:',
        'update_interval_colon': '更新间隔时间 (分钟):',
        'optional_default_input': '可选，留空使用默认',
        'optional_not_used_input': '可选，留空不使用',
        'stop_validate': '停止检测',
        'show_hidden': '恢复隐藏项',
        'retry_nth': '第{n}次重试',
        'generated_channel': '生成频道',
        'generated_group': '生成频道',
        'not_tested': '未检测',
        'now_playing': '正在播放',
        'no_program_desc': '暂无节目描述',
        'waiting_connect': '等待连接...',
        'switching_channel': '切换频道中...',
        'loading_program_info': '正在加载节目信息...',
        'catchup_current_program': '正在回看当前节目',
        'playing_current_channel': '正在播放当前频道',
        'playing_label': '播放中...',
        'unknown_program': '未知节目',
        'new_version_available': '有新版本',
        'new_version_found': '发现新版本',
        'preparing_play': '准备播放...',
        'no_current_program': '没有正在播放的节目',
        'catchup_supported': '支持回看',
        'catchup_available': '可回放',
        'timeshift_available': '可时移',
        'timeshift_watching': '正在时移观看',
        'timeshift_label': '时移',
        'catchup_label': '回看',
        'loading_from_cache': '从缓存加载列表数据',
        'dark_theme': '深色主题',
        'light_theme': '浅色主题',
        'scan': '扫描',
        'scan_total': '本次总数',
        'scan_progress': '扫描进度',
        'scan_completed': '扫描完成',
        'scan_nth': '第{n}次扫描',
        'validate': '检测',
        'validate_progress': '检测进度',
        'validate_completed': '检测完成',
        'validate_nth': '第{n}次检测',
        'all_channels_valid': '所有频道均有效',
        'retry_completed': '智能重试完成',
        'smart_retry': '智能重试',
        'retry_scan': '重试扫描',
        'mapping_manager': '频道映射管理器',
        'mapping_tip_title': '频道名称映射',
        'mapping_tip_desc': '远程映射会自动将扫描出的频道名称统一为标准名称。\n如果映射文件有更新，请点击下方按钮刷新。',
        'refresh_remote_cache': '刷新远程映射缓存',
        'refresh_remote_mapping': '刷新远程映射',
        'manual_mapping_section': '手动映射（高级）',
        'manual_mapping_hint': '仅当远程映射无法正确识别某个频道时才需要使用。',
        'export_user_mappings': '导出用户映射',
        'import_user_mappings': '导入用户映射',
        'close': '关闭',
        'search_channel_name': '搜索频道名...',
        'search': '搜索',
        'search_scope': '搜索范围',
        'search_all_fields': '搜索全部字段',
        'search_standard_name_only': '仅搜索标准名称',
        'search_raw_name_only': '仅搜索原始名称',
        'search_group_only': '仅搜索分组',
        'standard_name': '标准名称',
        'raw_name': '原始名称',
        'group': '分组',
        'logo_address': 'Logo地址',
        'add_mapping': '添加映射',
        'edit_mapping': '编辑映射',
        'delete_mapping': '删除映射',
        'fingerprint_id': '指纹ID',
        'mapped_name': '映射名称',
        'occurrence_count': '出现次数',
        'last_seen': '最后出现',
        'clear_fingerprint_data': '清空指纹数据',
        'analyze_unstable_mappings': '分析不稳定映射',
        'suggested_mapping': '建议映射',
        'confidence': '置信度',
        'operation': '操作',
        'refresh_suggestions': '刷新建议',
        'standard_name_placeholder': '输入标准频道名称',
        'raw_name_placeholder': '输入原始频道名称',
        'group_placeholder': '输入分组名称',
        'logo_url_placeholder': '输入Logo图片URL地址',
        'cache_refreshed': '远程映射缓存已刷新',
        'update_available': '发现新版本！点击上方按钮刷新。',
        'update_check_failed': '更新检查失败: {}',
        'mapping_status_ok': '已是最新 | 已加载: {} 条映射 | 上次: {}',
        'mapping_status_no_cache': '暂无缓存数据（已加载 {} 条映射）',
        'export_mappings_title': '导出映射',
        'exported_to': '已导出到',
        'import_mappings_title': '导入映射',
        'import_success': '用户映射已从CSV文件导入',
        'export_failed': '导出失败',
        'import_failed': '导入失败',
        'retry_options': '扫描重试选项',
        'enable_retry_scan': '启用重试扫描',
        'retry_scan_tooltip': '首次扫描完成后，重试扫描失败的频道',
        'loop_scan': '循环扫描',
        'loop_scan_tooltip': '如果重试扫描发现有效频道，继续扫描失败频道直到没有新的有效频道',
        'dark': '深色',
        'light': '浅色',
        'dark_blue': '暗蓝',
        'neumorphic_light': '拟态浅',
        'github_dark': 'GitHub 暗',
        'menu_hide_floating': '隐藏悬浮\tY',
        'menu_osd_toggle': '遮罩显隐\tTab',
        'tooltip_stay_on_top': '窗口置顶',
        'menu_reload_subscription': '重载订阅',
        'no_subscription_url': '未配置订阅地址',
        'reloading_subscription': '正在重新加载订阅...',
        'reload_subscription_failed': '重新加载订阅失败'
    },
    'en': {
        'language_name': 'English',
        'app_title': 'IPTV Scanner Editor Pro',
        'app_title_zh': 'IPTV Professional Scanner & Editor',
        'video_playback': 'Video Playback',
        'play': 'Play',
        'pause': 'Pause',
        'stop': 'Stop',
        'volume': 'Volume',
        'scan_settings': 'Scan Settings',
        'address_format': 'Address Format',
        'address_example': 'Address Example',
        'input_address': 'Input Address',
        'timeout_description': 'Set scan timeout (seconds)',
        'thread_count_description': 'Set number of scan threads',
        'user_agent': 'User-Agent',
        'referer': 'Referer',
        'progress': 'Progress',
        'timeout': 'Timeout',
        'thread_count': 'Thread Count',
        'scan_timeout': 'Timeout(s):',
        'scan_threads': 'Threads:',
        'full_scan': 'Full Scan',
        'stop_scan': 'Stop Scan',
        'generate_list': 'Generate List',
        'total_channels': 'Total Channels',
        'valid': 'Valid',
        'invalid': 'Invalid',
        'time_elapsed': 'Time Elapsed',
        'channel_list': 'Channel List',
        'validate_effectiveness': 'Validate Effectiveness',
        'hide_invalid': 'Hide Invalid',
        'smart_sort': 'Smart Sort',
        'please_load_list': 'Please load list first',
        'channel_edit': 'Channel Edit',
        'channel_name': 'Channel Name',
        'channel_group': 'Channel Group',
        'logo_address': 'Logo Address',
        'channel_url': 'Channel URL',
        'edit_channel': 'Edit Channel',
        'add_channel': 'Add Channel',
        'operation': 'Operation',
        'open_list': 'Open List',
        'save_list': 'Save List',
        'language': 'Language',
        'about': 'About',
        'required': 'Required',
        'optional': 'Optional',
        'optional_default': 'Optional, use default if empty',
        'optional_not_used': 'Optional, not used if empty',
        'serial_number': 'No.',
        'resolution': 'Resolution',
        'status': 'Status',
        'latency_ms': 'Latency(ms)',
        'tvg_id': 'TVG-ID',
        'tvg_chno': 'TVG Channel No.',
        'tvg_shift': 'TVG Shift',
        'catchup': 'Catchup',
        'catchup_days': 'Catchup Days',
        'catchup_source': 'Catchup Source',
        'catchup_correction': 'Catchup TZ Correction',
        'about_dialog_title': 'About IPTV Scanner Editor Pro',
        'current_version': 'Current Version',
        'latest_version': 'Latest Version',
        'build_date': 'Build Date',
        'qt_version': 'QT Version',
        'close_button': 'Close',
        'checking_update': 'Checking...',
        'update_timeout': 'Request Timeout',
        'update_failed': 'Failed to Fetch',
        'api_limit': 'API Limit',
        'update_progress_title': 'Online Update',
        'update_checking': 'Checking for updates...',
        'update_downloading': 'Downloading update...',
        'update_complete': 'Update downloaded, please restart the application',
        'update_error': 'Update Failed',
        'network_error': 'Network Error',
        'feature_intro': 'Main Features',
        'smart_scan': 'Smart Channel Scanning',
        'advanced_validation': 'Advanced Stream Validation',
        'intelligent_management': 'Intelligent Channel Management',
        'integrated_playback': 'Integrated Video Playback',
        'advanced_config': 'Advanced Configuration Management',
        'professional_tools': 'Professional Tools Integration',
        'usage_method': 'Usage Method',
        'scan_usage': 'Enter address format in scan settings, click "Full Scan" to start',
        'validation_usage': 'Open playlist and click "Validate Effectiveness" button',
        'management_usage': 'Right-click channel list or drag to adjust order',
        'playback_usage': 'Double-click any channel in the channel list',
        'config_usage': 'All settings are automatically saved, no manual operation required',
        'tools_usage': 'Access professional tools through the toolbar',
        'cancel_button': 'Cancel',
        'update_success': 'Update Complete',
        'file': 'File',
        'edit': 'Edit',
        'view': 'View',
        'tools': 'Tools',
        'help': 'Help',
        'new_playlist': 'New Playlist',
        'open_playlist': 'Open Playlist',
        'save_playlist': 'Save Playlist',
        'save_as': 'Save As...',
        'import_channels': 'Import Channels',
        'export_channels': 'Export Channels',
        'exit': 'Exit',
        'undo': 'Undo',
        'redo': 'Redo',
        'select_all': 'Select All',
        'delete_selected': 'Delete Selected',
        'show_epg': 'Show EPG',
        'show_playlist': 'Show Playlist',
        'fullscreen': 'Fullscreen',
        'refresh': 'Refresh',
        'reset_layout': 'Reset Layout',
        'scan_channels': 'Scan & Organize',
        'verify_channels': 'Verify Channels',
        'restore_hidden': 'Restore Hidden',
        'channel_management': 'Channel Management',
        'channel_mapping': 'Channel Mapping',
        'favorite_management': 'Favorite Management',
        'network_settings': 'Network Settings',
        'player_settings': 'Player Settings',
        'usage_instructions': 'Usage Instructions',
        'chinese': '中文',
        'english': 'English',
        'loading_channels': 'Loading channels...',
        'channels_loaded': 'Successfully loaded {count} channels',
        'file_format_error': 'File format is incorrect or empty',
        'open_file_error': 'Failed to open file: {error}',
        'save_success': 'Save successful',
        'save_error': 'Failed to save file: {error}',
        'no_content': 'No content to save',
        'file_selection_error': 'File selection failed: {error}',
        'app_name': 'IPTV Scanner Editor Pro',
        'version': 'Version 1.0.0',
        'description': 'IPTV channel scanning and editing tool',
        'usage_title': 'Usage Instructions',
        'usage_content': '## Basic Operations\n\n### 1. Open Playlist\n- File menu → Open Playlist (Ctrl+O)\n- Supports M3U, M3U8, TXT formats\n- Or drag and drop files onto the main window\n\n### 2. Play Channel\n- **Double-click** a channel in the list to start playing\n- Bottom control panel: ▶ Play / ▮▮ Pause / ■ Stop\n- Volume slider to adjust, click icon to mute/unmute\n- Speed button to change playback speed, aspect button for ratio\n- Fullscreen button or F11\n- **↑ ↓** keys to switch channels, **← →** keys to adjust volume\n\n### 3. EPG Program Guide\n- Left panel shows current channel program schedule\n- Click ◀ / ▶ to navigate dates\n- Progress bar shows current program playback position\n- Supports EPG data source auto-subscription updates\n- EPG URLs in M3U file headers are loaded automatically\n\n### 4. Scan & Organize\n- Tools menu → Scan & Organize\n- Enter IP range or stream URL (e.g. `239.3.1.[1-100]:8000`)\n- Set timeout and thread count, supports append scan and retry\n- After scanning, use **Batch Operations**:\n  - **Auto Classify**: Automatically group channels by name rules\n  - **Clean Names**: Remove brackets, HD suffixes, etc.\n  - **Match Logo**: Batch match channel logo images\n  - **Assign Fields**: Batch set group, logo and other attributes\n  - **Sort by Group**: Auto-sort channels by group\n\n### 5. Verify Channels\n- Batch check channel validity, show latency, resolution, etc.\n- Smart retry for failed items\n\n### 6. Channel Management\n- **Drag & Drop Sort**: Drag to reorder channels\n- **Group Filter**: Dropdown to filter by group\n- **Right-click Menu**: Delete, copy, clean names, match logos, etc.\n- **Channel Classification**: Auto-classify by regex rules\n- **Name Cleaning**: Smart removal of redundant info\n- **Export**: Save as M3U / TXT / Excel format\n\n## Advanced Features\n\n### Subscription Settings\n- Tools menu → Subscription Settings\n- Configure multiple playlist and EPG sources, managed independently\n- Auto-refresh on expiry and incremental updates\n- RTSP transport: TCP/UDP/LAVF selectable\n\n### Channel Mapping\n- Tools menu → Channel Mapping Manager\n- Visual editing of name, LOGO, group mapping rules\n\n### File Association\n- Tools menu → File Association\n- Check formats to associate (M3U/M3U8/TXT/Video formats)\n- Right-click files in Explorer to open with this program\n\n### Interface Customization\n- **Theme Switching**: 5 themes available\n- **Language Switching**: Chinese / English\n- **Panel Control**: View menu or shortcuts\n  - **E** — EPG panel\n  - **L** — Channel list panel\n  - **M** — Control panel\n  - **Y** — Hide/restore all floating panels\n  - **Tab** — Toggle OSD info overlay\n- **F5** Refresh, **F11** Fullscreen, **Ctrl+Q** Exit\n\n### Timeshift / Catchup\n- Multiple catchup types: default / append / shift / flussonic / xc\n- Time variable replacement with custom format and timezone offset\n- M3U file headers can define global catchup parameters',
        'about_title': 'About',
        'about_content': 'IPTV Scanner Editor Pro\nVersion 1.0.0\n\nIPTV channel scanning and editing tool\n\n© 2026 IPTV Scanner Editor Pro',
        'epg_title': 'Program Guide',
        'not_playing': 'Not playing',
        'language_changed': 'Language changed',
        'no_epg_data': 'No program information',
        'no_channels': 'No channels',
        'media_info': 'Media Info',
        'menu_file': 'File',
        'menu_open_playlist': 'Open Playlist\tCtrl+O',
        'menu_open_stream': 'Open Stream\tCtrl+U',
        'menu_open_video': 'Open Video\tCtrl+Shift+O',
        'open_stream': 'Open Stream',
        'open_stream_url': 'Enter stream URL:',
        'open_video': 'Open Video',
        'video_files': 'Video Files (*.mp4 *.mkv *.avi *.mov *.flv *.wmv *.ts *.webm);;All Files (*)',
        'temp_stream': 'Temp Stream',
        'stream_name_optional': 'Channel name (optional):',
        'stream_name_hint': 'Leave empty for auto name',
        'cancel': 'Cancel',
        'ok': 'OK',
        'local_video': 'Local Video',
        'local_video_file': 'Local Video File',
        'menu_recent_open': 'Recent',
        'menu_save_as': 'Save As...\tCtrl+S',
        'menu_exit': 'Exit\tCtrl+Q',
        'menu_view': 'View',
        'menu_epg_list': 'EPG List\tE',
        'menu_playlist': 'Playlist\tL',
        'menu_control_panel': 'Control Panel\tM',
        'menu_fullscreen': 'Fullscreen\tF11',
        'menu_pip': 'Picture-in-Picture\tP',
        'menu_multi_screen': 'Multi Screen',
        'menu_multi_2x2': '2×2 (4 Screens)',
        'menu_multi_3x3': '3×3 (9 Screens)',
        'menu_multi_exit': 'Exit Multi Screen',
        'multi_screen_entered': 'Multi screen mode entered',
        'multi_screen_exited': 'Multi screen mode exited',
        'search_channel': 'Search channels...',
        'epg_no_catchup': 'Catchup not supported',
        'epg_upcoming': 'Program not started yet',
        'epg_date_limit': 'Date range limit reached',
        'exit_catchup': 'Exit Catchup',
        'panel_prev_ch': 'Prev Channel',
        'panel_next_ch': 'Next Channel',
        'panel_pip': 'PiP',
        'tooltip_minimize': 'Minimize',
        'tooltip_maximize': 'Maximize',
        'tooltip_close': 'Close',
        'menu_refresh': 'Refresh\tF5',
        'menu_reset_layout': 'Reset Layout',
        'menu_playback': 'Playback',
        'menu_prev_channel': 'Previous Channel\t↑',
        'menu_next_channel': 'Next Channel\t↓',
        'menu_prev_channel2': 'Previous Channel (Alt)\tCtrl+Shift+↑',
        'menu_next_channel2': 'Next Channel (Alt)\tCtrl+Shift+↓',
        'menu_back_channel': 'Switch Back\tBackspace',
        'menu_play_pause': 'Play/Pause\tSpace',
        'menu_stop': 'Stop\tEsc',
        'menu_seek_back': 'Seek Back\t←',
        'menu_seek_forward': 'Seek Forward\t→',
        'menu_vol_up': 'Volume Up\tScroll Up',
        'menu_vol_down': 'Volume Down\tScroll Down',
        'menu_mute': 'Mute\tCtrl+M',
        'menu_speed_up': 'Speed Up\t.',
        'menu_speed_down': 'Speed Down\t,',
        'menu_screenshot': 'Screenshot\tS',
        'osd_volume': 'Volume',
        'osd_muted': 'Muted',
        'osd_speed': 'Speed',
        'osd_audio_track': 'Audio',
        'osd_audio_track_failed': 'Audio track switch failed',
        'osd_subtitle_track': 'Subtitle',
        'osd_subtitle_track_failed': 'Subtitle track switch failed',
        'ctx_pause': 'Pause',
        'ctx_play': 'Play',
        'ctx_stop': 'Stop',
        'ctx_prev_channel': 'Previous Channel',
        'ctx_next_channel': 'Next Channel',
        'ctx_speed': 'Speed',
        'ctx_volume': 'Volume',
        'ctx_mute': 'Mute',
        'ctx_unmute': 'Unmute',
        'ctx_aspect_ratio': 'Aspect Ratio',
        'ctx_aspect_default': 'Default',
        'ctx_aspect_stretch': 'Stretch',
        'ctx_aspect_fill': 'Fill',
        'ctx_screenshot': 'Screenshot\tS',
        'ctx_fullscreen': 'Fullscreen\tF11',
        'ctx_pip': 'Picture-in-Picture\tP',
        'ctx_view': 'View',
        'ctx_epg': 'EPG List\tE',
        'ctx_playlist': 'Playlist\tL',
        'ctx_control_panel': 'Control Panel\tM',
        'ctx_hide_panels': 'Hide Floating Panels\tY',
        'ctx_reset_layout': 'Reset Layout',
        'ctx_open_stream': 'Open Stream\tCtrl+U',
        'ctx_open_video': 'Open Video\tCtrl+Shift+O',
        'ctx_scan': 'Scan & Organize',
        'ctx_audio_track': 'Audio Track',
        'ctx_no_audio_track': 'No Audio Tracks',
        'ctx_subtitle': 'Subtitle',
        'ctx_no_subtitle': 'No Subtitle',
        'ctx_load_subtitle': 'Load Subtitle...',
        'ctx_subtitle_files': 'Subtitle Files',
        'ctx_all_files': 'All Files',
        'panel_audio_track': 'Audio Track',
        'panel_subtitle': 'Subtitle',
        'menu_tools': 'Tools',
        'menu_scan_channels': 'Scan & Organize',
        'menu_mapping': 'Mapping',
        'menu_subscription_settings': 'Subscription Settings',
        'menu_file_association': 'File Association',
        'file_assoc_title': 'Select file formats to associate',
        'file_assoc_hint': 'After registration, right-click files to open with this program',
        'file_association': 'File Association',
        'menu_theme': 'Theme',
        'menu_help': 'Help',
        'menu_instructions': 'Instructions',
        'menu_about': 'About',
        'today': 'Today',
        'yesterday': 'Yesterday',
        'tomorrow': 'Tomorrow',
        'no_channel_selected': 'No channel selected',
        'select_channel_to_play': 'Select a channel to play',
        'open_playlist_or_import': 'Open a playlist file or import channels to start watching',
        'waiting_to_play': 'Waiting to play...',
        'exit_catchup': 'Exit Catchup',
        'playing': 'Playing',
        'paused': 'Paused',
        'stopped': 'Stopped',
        'play_error': 'Play Error',
        'pip_mode': 'PiP Mode',
        'to_exit': 'to exit',
        'pip_exited': 'exited',
        'playing_channel': 'Playing: {name}',
        'paused_channel': 'Paused: {name}',
        'stopped_play': 'Stopped',
        'playback_stopped': 'Playback stopped',
        'catchup_playing': 'Catchup: {name}',
        'catchup_paused': 'Catchup Paused: {name}',
        'subscription_settings_title': 'Subscription Settings',
        'protocol_settings': 'Protocol Settings',
        'protocol_type': 'Protocol Type',
        'rtsp_transport_colon': 'RTSP Transport:',
        'hwdec_label': 'Hardware Decoding',
        'tls_verify_label': 'TLS Verify',
        'network_timeout_colon': 'Network Timeout:',
        'auto_timeout': 'Auto',
        'playlist_subscription': 'Playlist Subscription',
        'subscription_url': 'Subscription URL',
        'subscription_name': 'Subscription Name',
        'update_interval': 'Update Interval (min)',
        'epg_subscription': 'EPG Subscription (all sources will be merged automatically)',
        'playlist_sources': 'Playlist Sources (click to activate):',
        'epg_sources': 'EPG Sources:',
        'add_source': '+ Add Source',
        'update_source': '✎ Update',
        'remove_source': '- Remove Selected',
        'enter_source_name': 'Source name (optional)',
        'epg_loaded': 'EPG data loaded successfully',
        'save_button': 'Save',
        'usage_instructions_title': 'Usage Instructions',
        'ok_button': 'OK',
        'loading': 'Loading...',
        'current_program': 'Now Playing',
        'upcoming_program': 'Upcoming',
        'finished_program': 'Ended',
        'bitrate_unknown': 'Unknown',
        'codec_unknown': 'Unknown',
        'resolution_unknown': 'Unknown',
        'back_to_live': 'Back to Live',
        'cannot_seek_live': 'Cannot seek back: live stream buffer insufficient (try again later)',
        'timeshift_beyond_cache': 'Beyond buffer range, cannot seek to earlier time',
        'timeshift_beyond_cache_no_epg': 'Beyond buffer range, no EPG info, cannot auto-timeshift',
        'timeshift_playing': 'Timeshifting',
        'ready': 'Ready',
        'catchup_not_supported': 'This channel does not support catchup',
        'playlist_sub_updated': 'Playlist subscription updated',
        'playlist_sub_parse_failed': 'Playlist subscription parse failed',
        'playlist_sub_update_failed': 'Failed to update playlist subscription',
        'player_settings_saved': 'Player settings saved',
        'player_settings_save_failed': 'Failed to save player settings',
        'epg_settings_saved': 'EPG settings saved',
        'file_opened': 'File opened',
        'file_open_failed': 'Failed to open file',
        'file_not_found': 'File not found, removed from recent list',
        'language_change_failed': 'Language change failed',
        'theme_changed': 'Theme changed to',
        'theme_change_failed': 'Theme change failed',
        'epg_sub_updated': 'EPG subscription updated',
        'epg_sub_parse_failed': 'EPG subscription parse failed',
        'epg_sub_update_failed': 'Failed to update EPG subscription',
        'epg_using_cache': 'Using cached EPG data',
        'codec_label': 'Codec',
        'resolution_label': 'Resolution',
        'bitrate_label': 'Bitrate',
        'channel_count_label': 'Channels',
        'sample_rate_label': 'Sample Rate',
        'format_label': 'Format',
        'protocol_label': 'Protocol',
        'frame_rate_label': 'FPS',
        'hwdec_label': 'HW',
        'vcodec_label': 'Video',
        'acodec_label': 'Audio',
        'hdr_label': 'HDR',
        'no_video_info': 'No video info',
        'no_audio_info': 'No audio info',
        'no_network_info': 'No network info',
        'pixel_format_label': 'Pixel Format',
        'hdr_type': 'Dynamic Range',
        'hdr_sdr': 'SDR',
        'hdr_hlg': 'HLG',
        'hdr_hdr10': 'HDR10',
        'hdr_hdr10_plus': 'HDR10+',
        'hdr_dv': 'Dolby Vision',
        'player_settings_title': 'Player Settings',
        'update_interval_minutes': 'Update interval (minutes)',
        'enter_playlist_url': 'Enter playlist subscription URL',
        'enter_subscription_name': 'Enter subscription name',
        'enter_epg_url': 'Enter EPG subscription URL',
        'epg_settings_title': 'EPG Settings',
        'epg_url_label': 'EPG URL',
        'epg_source_label': 'EPG Source',
        'app_description': 'IPTV Professional Scanner & Editor',
        'system_info': 'System Info',
        'copyright_text': '© 2025 IPTV Scanner Editor Pro',
        'github_repo': 'GitHub Repository',
        'request_timeout_text': '(Request Timeout)',
        'fetch_failed_text': '(Fetch Failed)',
        'api_limit_text': '(API Limit)',
        'scan_settings_title': 'Scan Settings',
        'channel_list_title': 'Channel List',
        'channel_edit_title': 'Channel Edit',
        'scan_window_title': 'IPTV Scanner',
        'validate_button': 'Validate',
        'hide_invalid_button': 'Hide Invalid',
        'save_m3u': 'Save M3U',
        'save_txt': 'Save TXT',
        'save_m3u_tooltip': 'Save channel list as M3U format',
        'save_txt_tooltip': 'Save channel list as TXT format',
        'batch_ops': 'Batch Ops',
        'batch_ops_tooltip': 'Batch operations for channels',
        'auto_classify': 'Auto Classify',
        'clean_names': 'Clean Names',
        'assign_fields': 'Assign Fields',
        'match_logo': 'Match Logo',
        'clear_params': 'Clear Params',
        'sort_by_group': 'Sort by Group',
        'local_province': 'Local Province:',
        'overwrite_existing': 'Overwrite existing groups',
        'merge_nonlocal': 'Merge non-local to Other',
        'preview_count': 'Preview:',
        'channel_name': 'Channel Name',
        'old_group': 'Old Group',
        'new_group': 'New Group',
        'preview': 'Preview',
        'apply': 'Apply',
        'cancel': 'Cancel',
        'before': 'Before',
        'after': 'After',
        'only_empty_fields': 'Only assign to empty fields',
        'target_channels': 'Target:',
        'overwrite_logo_confirm': 'Overwrite existing logos?',
        'move_to_group': 'Move to Group...',
        'clean_selected_names': 'Clean Selected Names',
        'match_selected_logo': 'Match Selected Logo',
        'target_group': 'Target Group:',
        'save_scan_result': 'Save Scan Result',
        'no_channels_to_save': 'No channels to save',
        'append_scan': 'Append Scan',
        'address_format_hint': 'Format: http://ip:port/rtp/10.10.[1-20].[1-20]:5002',
        'timeout_small': 'Timeout',
        'thread_small': 'Threads',
        'scan_retry_options': 'Scan Retry Options',
        'enable_smart_retry': 'Enable Smart Retry',
        'mapping_options': 'Mapping Options',
        'enable_channel_mapping': 'Enable Channel Mapping',
        'save_changes': 'Save Changes',
        'copy_channel_name': 'Copy Channel Name',
        'copy_url': 'Copy URL',
        'copy_tvg_id': 'Copy TVG-ID',
        'copy_group': 'Copy Group',
        'delete_channel': 'Delete Channel',
        'confirm_delete': 'Confirm Delete',
        'confirm_delete_mapping': 'Confirm Delete Mapping',
        'confirm_delete_message': 'Are you sure you want to delete the selected channel?',
        'select_mapping_to_edit': 'Please select a mapping to edit',
        'select_mapping_to_delete': 'Please select a mapping to delete',
        'delete_mapping_confirm': "Delete mapping '{}' → '{}'?",
        'scan_complete': 'Scan Complete',
        'append_scan_tooltip': 'Append valid channels to existing list without clearing',
        'smart_retry_tooltip': 'Smart retry based on failure reasons: only retry timeout and connection failures, not TCP failures or 404 errors. Automatically loops until no new valid channels found',
        'mapping_tooltip': 'When enabled, scanned channels will auto-match name, logo, group from mapping file',
        'set_scan_timeout': 'Set scan timeout (seconds)',
        'set_scan_threads': 'Set number of scan threads',
        'validate_tooltip': 'Validate channel effectiveness',
        'no_recent_files': 'No recent files',
        'select_channel_play': 'Select a channel to play',
        'open_playlist_success': 'Playlist opened, click a channel to play',
        'catchup_playing_label': 'Catching up',
        'unknown_channel': 'Unknown Channel',
        'unnamed': 'Unnamed',
        'uncategorized': 'Uncategorized',
        'all_channels': 'All Channels',
        'subscription_tab': 'Subscription',
        'local_tab': 'Local',
        'media_info_label': 'Media Info',
        'epg_url_colon': 'EPG URL:',
        'epg_source_colon': 'EPG Source:',
        'protocol_type_colon': 'Protocol Type:',
        'subscription_url_colon': 'Subscription URL:',
        'subscription_name_colon': 'Subscription Name:',
        'update_interval_colon': 'Update interval (minutes):',
        'optional_default_input': 'Optional, use default if empty',
        'optional_not_used_input': 'Optional, not used if empty',
        'stop_validate': 'Stop Validate',
        'show_hidden': 'Show Hidden',
        'retry_nth': 'Retry #{n}',
        'generated_channel': 'Generated Channel',
        'generated_group': 'Generated',
        'not_tested': 'Not Tested',
        'now_playing': 'Now Playing',
        'no_program_desc': 'No program description',
        'waiting_connect': 'Waiting to connect...',
        'switching_channel': 'Switching channel...',
        'loading_program_info': 'Loading program info...',
        'catchup_current_program': 'Catching up current program',
        'playing_current_channel': 'Playing current channel',
        'playing_label': 'Playing...',
        'unknown_program': 'Unknown Program',
        'new_version_available': 'New Version Available',
        'new_version_found': 'New version found',
        'preparing_play': 'Preparing to play...',
        'no_current_program': 'No current program',
        'catchup_supported': 'Catchup supported',
        'catchup_available': 'Catchup',
        'timeshift_available': 'Timeshift',
        'timeshift_watching': 'Timeshift watching',
        'timeshift_label': 'Timeshift',
        'catchup_label': 'Catchup',
        'loading_from_cache': 'Loading from cache',
        'dark_theme': 'Dark Theme',
        'light_theme': 'Light Theme',
        'scan': 'Scan',
        'scan_total': 'Total This Scan',
        'scan_progress': 'Scan Progress',
        'scan_completed': 'Scan Completed',
        'scan_nth': 'Scan #{n}',
        'validate': 'Validate',
        'validate_progress': 'Validate Progress',
        'validate_completed': 'Validate Completed',
        'validate_nth': 'Validate #{n}',
        'all_channels_valid': 'All channels are valid',
        'retry_completed': 'Smart retry completed',
        'smart_retry': 'Smart Retry',
        'retry_scan': 'Retry Scan',
        'mapping_manager': 'Channel Mapping Manager',
        'mapping_tip_title': 'Channel Name Mapping',
        'mapping_tip_desc': 'Remote mapping automatically standardizes channel names.\nIf the mapping file is updated, click the button below to refresh.',
        'refresh_remote_cache': 'Refresh Remote Cache',
        'refresh_remote_mapping': 'Refresh Remote Mapping',
        'manual_mapping_section': 'Manual Mapping (Advanced)',
        'manual_mapping_hint': 'Only needed when remote mapping cannot correctly identify a channel.',
        'export_user_mappings': 'Export User Mappings',
        'import_user_mappings': 'Import User Mappings',
        'close': 'Close',
        'search_channel_name': 'Search channel name...',
        'search': 'Search',
        'search_scope': 'Search Scope',
        'search_all_fields': 'Search All Fields',
        'search_standard_name_only': 'Search Standard Name Only',
        'search_raw_name_only': 'Search Raw Name Only',
        'search_group_only': 'Search Group Only',
        'standard_name': 'Standard Name',
        'raw_name': 'Raw Name',
        'group': 'Group',
        'logo_address': 'Logo Address',
        'add_mapping': 'Add Mapping',
        'edit_mapping': 'Edit Mapping',
        'delete_mapping': 'Delete Mapping',
        'fingerprint_id': 'Fingerprint ID',
        'mapped_name': 'Mapped Name',
        'occurrence_count': 'Occurrence Count',
        'last_seen': 'Last Seen',
        'clear_fingerprint_data': 'Clear Fingerprint Data',
        'analyze_unstable_mappings': 'Analyze Unstable Mappings',
        'suggested_mapping': 'Suggested Mapping',
        'confidence': 'Confidence',
        'operation': 'Operation',
        'refresh_suggestions': 'Refresh Suggestions',
        'standard_name_placeholder': 'Enter standard channel name',
        'raw_name_placeholder': 'Enter raw channel name',
        'group_placeholder': 'Enter group name',
        'logo_url_placeholder': 'Enter logo URL',
        'cache_refreshed': 'Remote mapping cache refreshed',
        'update_available': 'New version available! Click the button above to refresh.',
        'update_check_failed': 'Update check failed: {}',
        'mapping_status_ok': 'Up to date | Loaded: {} mappings | Last: {}',
        'mapping_status_no_cache': 'No cached data yet ({} mappings loaded)',
        'export_mappings_title': 'Export Mappings',
        'exported_to': 'Exported to',
        'import_mappings_title': 'Import Mappings',
        'import_success': 'Mappings imported successfully',
        'export_failed': 'Export failed',
        'import_failed': 'Import failed',
        'retry_options': 'Scan Retry Options',
        'enable_retry_scan': 'Enable Retry Scan',
        'retry_scan_tooltip': 'After the first scan completes, retry scanning failed channels',
        'loop_scan': 'Loop Scan',
        'loop_scan_tooltip': 'If retry scan finds valid channels, continue scanning failed channels until no new valid channels are found',
        'dark': 'Dark',
        'light': 'Light',
        'dark_blue': 'Dark Blue',
        'neumorphic_light': 'Neumorphic Light',
        'github_dark': 'GitHub Dark',
        'menu_hide_floating': 'Hide Floating Panels\tY',
        'menu_osd_toggle': 'OSD Mask\tTab',
        'tooltip_stay_on_top': 'Stay on Top',
        'menu_reload_subscription': 'Reload Subscription',
        'no_subscription_url': 'No subscription URL configured',
        'reloading_subscription': 'Reloading subscription...',
        'reload_subscription_failed': 'Failed to reload subscription'
    }
}


class _LanguageSignalHelper(QObject):
    language_changed = pyqtSignal()


class LanguageManager(Singleton):

    def __init__(self):
        if self._initialized:
            return
        self._signal_helper = _LanguageSignalHelper()
        self._lock = threading.Lock()
        self.current_language = 'zh'
        self.translations = {}
        self.available_languages = {}
        self._initialized = True

    @property
    def language_changed(self):
        return self._signal_helper.language_changed

    def load_available_languages(self):
        if hasattr(self, '_languages_loaded') and self._languages_loaded:
            return self.available_languages

        self.available_languages = {}
        for lang_code, data in BUILTIN_TRANSLATIONS.items():
            self.available_languages[lang_code] = {
                'file': f'builtin:{lang_code}',
                'display_name': data.get('language_name', lang_code),
                'data': data
            }

        loaded_languages = list(self.available_languages.keys())
        logger.debug(f"成功加载 {len(loaded_languages)} 种内置语言: {', '.join(loaded_languages)}")

        self._languages_loaded = True
        return self.available_languages

    def set_language(self, lang_code):
        with self._lock:
            if lang_code in self.available_languages:
                self.current_language = lang_code
                self.translations = self.available_languages[lang_code]['data']
            else:
                logger.warning(f"语言 {lang_code} 不可用")
                return False
        self.language_changed.emit()
        return True

    def get_translation(self, key, default=None):
        with self._lock:
            return self.translations.get(key, default)

    @overload
    def tr(self, key: str, default: str) -> str: ...

    @overload
    def tr(self, key: str, default: None = None) -> str | None: ...

    def tr(self, key, default=None):
        return self.get_translation(key, default)

    def get_language_list(self):
        languages = []
        for lang_code, lang_info in self.available_languages.items():
            languages.append({
                'code': lang_code,
                'name': lang_info['display_name'],
                'file': lang_info['file']
            })
        return languages

    def update_ui_texts(self, main_window):
        if not self.translations:
            return

        try:
            from ui.dialogs.about_dialog import AboutDialog
            version = AboutDialog.CURRENT_VERSION
            new_title = f"{self.tr('app_title', 'IPTV Scanner Editor Pro')} v{version}"
            main_window.setWindowTitle(new_title)
            # 同步更新自定义标题栏标签（无边框窗口 setWindowTitle 不可见）
            if hasattr(main_window, '_title_label') and main_window._title_label:
                main_window._title_label.setText(new_title)

            if hasattr(main_window, 'epg_title'):
                main_window.epg_title.setText(f"📅 {self.tr('epg_title', 'Program Guide')}")
            if hasattr(main_window, 'epg_date_label'):
                current_text = main_window.epg_date_label.text()
                zh_day_map = {'今天': 'today', '昨天': 'yesterday', '明天': 'tomorrow'}
                en_day_map = {'Today': 'today', 'Yesterday': 'yesterday', 'Tomorrow': 'tomorrow'}
                day_key = zh_day_map.get(current_text) or en_day_map.get(current_text)
                if day_key:
                    main_window.epg_date_label.setText(self.tr(day_key, current_text))
            if hasattr(main_window, 'epg_empty_label'):
                main_window.epg_empty_label.setText(self.tr('no_epg_data', 'No program information'))

            if hasattr(main_window, 'playlist_tab'):
                main_window.playlist_tab.setTabText(0, self.tr('subscription_tab', 'Subscription'))
                main_window.playlist_tab.setTabText(1, self.tr('local_tab', 'Local'))
            for empty_attr in ['sub_empty_label', 'local_empty_label']:
                el = getattr(main_window, empty_attr, None)
                if el:
                    el.setText(self.tr('no_channels', 'No channels'))

            if hasattr(main_window, 'video_info'):
                main_window.video_info.setText(self.tr('not_playing', 'Not playing'))
            if hasattr(main_window, 'audio_info'):
                main_window.audio_info.setText("--")
            if hasattr(main_window, 'network_info'):
                main_window.network_info.setText("--")

            if hasattr(main_window, 'channel_name'):
                main_window.channel_name.setText(self.tr('no_channel_selected', 'No channel selected'))
            if hasattr(main_window, 'current_program'):
                main_window.current_program.setText("")
            if hasattr(main_window, 'program_desc'):
                main_window.program_desc.setText(self.tr('open_playlist_or_import', 'Open a playlist file or import channels to start watching'))
            if hasattr(main_window, 'remain_label'):
                main_window.remain_label.setText(self.tr('waiting_to_play', 'Waiting to play...'))
            if hasattr(main_window, 'exit_catchup_button'):
                main_window.exit_catchup_button.setText(self.tr('exit_catchup', '⏪ Exit Catchup'))

            self._update_dialogs(main_window)

            logger.info(f"UI文本已更新到语言: {self.current_language}")

        except Exception as e:
            logger.error(f"更新UI文本失败: {str(e)}")

    def _update_dialogs(self, main_window):
        try:
            from PyQt6 import QtWidgets
            for widget in main_window.findChildren(QtWidgets.QDialog):
                if hasattr(widget, 'update_ui_texts'):
                    widget.update_ui_texts()
        except Exception as e:
            logger.debug(f"更新对话框失败: {e}")
